In [2]:
import superannotate as sa

In [3]:
sa.aggregate_annotations_as_df("../tests/sample_project_vector/")

SA-PYTHON-SDK - INFO - Aggregating annotations from ../tests/sample_project_vector/ as pandas dataframe

,imageName,instanceId,className,attributeGroupName,attributeName,type,error,locked,visible,trackingId,probability,pointLabels,meta
0,example_image_3.jpg,1,Personal vehicle,None,None,polygon,None,False,True,None,100.0,None,"{'points': [0.39, 272.46, 4.33, 260.62, 30.82,..."
1,example_image_3.jpg,2,Personal vehicle,None,None,polygon,None,False,True,None,100.0,None,"{'points': [1198.84, 310.57, 1099.1, 298.81, 1..."
2,example_image_3.jpg,3,Personal vehicle,None,None,polygon,None,False,True,None,100.0,None,"{'points': [981.04, 326.53, 979.55, 317.59, 97..."
3,example_image_3.jpg,4,Personal vehicle,None,None,polygon,None,False,True,None,100.0,None,"{'points': [653.44, 240.81, 656.42, 217.7, 703..."
4,example_image_3.jpg,5,Personal vehicle,None,None,polygon,None,False,True,None,100.0,None,"{'points': [770.09, 156.21, 763.76, 153.23, 68..."
...,...,...,...,...,...,...,...,...,...,...,...,...,...
69,example_image_4.jpg,10,Personal vehicle,None,None,polygon,None,False,True,None,100.0,None,"{'points': [12.52, 102.15, 17.66, 94.48, 15.77..."
70,example_image_4.jpg,11,Large vehicle,None,None,polygon,None,False,True,None,100.0,None,"{'points': [0.41, 101.91, 57.82, 107.46, 58.02..."
71,example_image_4.jpg,12,Large vehicle,None,None,polygon,None,False,True,None,100.0,None,"{'points': [222.23, 143.48, 232.31, 141.21, 23..."
72,example_image_4.jpg,13,Large vehicle,None,None,polygon,None,False,True,None,100.0,None,"{'points': [303.1, 192.66, 304.75, 181.96, 307..."
73,example_image_4.jpg,14,Large vehicle,None,None,polygon,None,False,True,None,100.0,None,"{'points': [462.58, 200.89, 463.2, 193.07, 468..."